import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { TimelineItem } from "@/lib/timeline";

interface VehicleInfo {
  vrm: string;
  make: string | null;
  model: string | null;
  colour: string | null;
  fuel_type: string | null;
}

const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 56,
    paddingHorizontal: 44,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  wordmark: { fontSize: 14, fontFamily: "Helvetica-Bold", marginBottom: 16 },
  wordmarkAccent: { color: "#1E4FD8" },
  title: { fontSize: 18, marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#555555", marginBottom: 20 },
  row: {
    flexDirection: "row",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
    paddingVertical: 8,
  },
  date: { width: 70, color: "#555555" },
  // flexBasis: 0 alongside flexGrow is the part that actually matters
  // here — without it, Yoga sizes this column to its content instead
  // of the space the row has for it, so long unbroken text (a note, a
  // defect description) overflows past the page's right padding
  // instead of wrapping.
  rowBody: { flexDirection: "column", flexGrow: 1, flexBasis: 0 },
  label: { fontFamily: "Helvetica-Bold" },
  meta: { color: "#555555", marginTop: 2 },
  pass: { color: "#15803d" },
  fail: { color: "#b91c1c" },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 44,
    right: 44,
    fontSize: 8,
    color: "#999999",
    textAlign: "center",
  },
});

export function VehicleHistoryDocument({
  vehicle,
  timeline,
}: {
  vehicle: VehicleInfo;
  timeline: TimelineItem[];
}) {
  const generatedAt = new Date().toISOString().slice(0, 10);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.wordmark}>
          Motor<Text style={styles.wordmarkAccent}>360</Text>
        </Text>
        <Text style={styles.title}>{vehicle.vrm}</Text>
        <Text style={styles.subtitle}>
          {[vehicle.make, vehicle.model, vehicle.colour, vehicle.fuel_type]
            .filter(Boolean)
            .join(" · ") || "Motor360 vehicle history"}
        </Text>

        {timeline.length === 0 ? (
          <Text>No history recorded yet.</Text>
        ) : (
          timeline.map((item) =>
            item.kind === "mot" ? (
              <View key={`mot-${item.entry.id}`} style={styles.row}>
                <Text style={styles.date}>{item.entry.test_date}</Text>
                <View style={styles.rowBody}>
                  <Text style={styles.label}>
                    MOT test —{" "}
                    <Text
                      style={
                        item.entry.result === "PASS" ? styles.pass : styles.fail
                      }
                    >
                      {item.entry.result === "PASS" ? "Pass" : "Fail"}
                    </Text>
                  </Text>
                  {item.entry.odometer_value != null && (
                    <Text style={styles.meta}>
                      {item.entry.odometer_value.toLocaleString()}{" "}
                      {item.entry.odometer_unit}
                    </Text>
                  )}
                  {(item.entry.raw_data?.defects ?? []).map((defect, index) => (
                    <Text key={index} style={styles.meta}>
                      • [{defect.type}] {defect.text}
                    </Text>
                  ))}
                </View>
              </View>
            ) : (
              <View key={`service-${item.entry.id}`} style={styles.row}>
                <Text style={styles.date}>{item.entry.entry_date}</Text>
                <View style={styles.rowBody}>
                  <Text style={styles.label}>
                    {item.entry.service_type[0].toUpperCase() +
                      item.entry.service_type.slice(1)}
                    {item.entry.verified ? "  (Verified)" : ""}
                  </Text>
                  {item.entry.mileage != null && (
                    <Text style={styles.meta}>
                      {item.entry.mileage.toLocaleString()} mi
                    </Text>
                  )}
                  {item.entry.garage_name && (
                    <Text style={styles.meta}>{item.entry.garage_name}</Text>
                  )}
                  {item.entry.notes && (
                    <Text style={styles.meta}>{item.entry.notes}</Text>
                  )}
                </View>
              </View>
            ),
          )
        )}

        <Text style={styles.footer} fixed>
          Generated by Motor360 on {generatedAt}. Reflects the Motor360 record
          at time of export; attached invoice files are not included.
        </Text>
      </Page>
    </Document>
  );
}
